name: Update NRW-Schulferien-Feed

on:
  schedule:
    - cron: '0 3 * * *'       # Täglich um 03:00 UTC
  workflow_dispatch:         # Manuelles Auslösen möglich

permissions:
  contents: write            # Erlaubt Commit & Push ins Repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo auschecken
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Abhängigkeiten installieren
        run: pip install requests ics

      - name: ICS generieren
        run: python templates/ferien2ics.py > NRW_Schulferien.ics

      - name: Änderungen committen & pushen
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          file_pattern: 'NRW_Schulferien.ics'
          commit_message: 'Auto-Update NRW_Schulferien.ics'

